### ISSUE TITLE
Server crash on startup

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [eideehi/mc-experiencebottler#2]
**MC** 1.17.1
**Fabric** loader 0.12.5; API 0.42.1
**Experience bottler** 1.17.1-2

> [06:37:26] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'experiencebottler'!
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.61) ~[?:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[server.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[server.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[server.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[server.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[server.jar:?]
	at net.minecraft.server.Main.main(Main:97) [intermediary-vanilla.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568) [server.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [server.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [server.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:72) [server.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:98) [server.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:60) [server.jar:?]
Caused by: java.lang.NoSuchMethodError: 'void net.eidee.minecraft.experiencebottler.screen.ExperienceBottlerScreenHandler.<init>(int, net.minecraft.class_1661)'
	at net.eidee.minecraft.experiencebottler.screen.ScreenHandlers.init(ScreenHandlers.java:55) ~[experiencebottler-1.17.1-2.jar:?]
	at net.eidee.minecraft.experiencebottler.core.init.ScreenInitializer.init(ScreenInitializer.java:39) ~[experiencebottler-1.17.1-2.jar:?]
	at net.eidee.minecraft.experiencebottler.core.init.ModInitializer.onInitialize(ModInitializer.java:35) ~[experiencebottler-1.17.1-2.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[server.jar:?]
	... 17 more

**Comment by eideehi** [comment]
Thanks for the report! I guess they know I haven't tested it on server. I will fix it. Don't worry, I will test it properly on the server this time.
